spring:
  application:
    name: cloud-manager
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloud_manager_db}
    username: ${SPRING_DATASOURCE_USERNAME:cloud_user}
    password: ${SPRING_DATASOURCE_PASSWORD:cloud_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      credentials:
        access-key: mock-key
        secret-key: mock-secret
      region:
        static: us-east-1
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT:http://localhost:9324}
      s3:
        enabled: false
      parameter-store:
        enabled: false
      secrets-manager:
        enabled: false

aws:
  sqs:
    queue-name: account-provisioning-queue
